title: Testing With Edd
email: edd@testingwithedd.com
description: >-
  A blog about software testing, automation, and infrastructure.
baseurl: ""
url: "https://testingwithedd.github.io"
github_username:  testingwithedd

favicon: "favicon.png"
goat_counter: "testingwithedd"

# Build settings
theme: no-style-please
plugins:
  - jekyll-feed

theme_config:
  appearance: "auto" 
  back_home_text: ".." 
  date_format: "%Y-%m-%d"
  show_description: false

sass:
  style: :compressed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
